server:
  port: 8080
  servlet:
    context-path: /app
spring:
  datasource:
    username: default
    password: 9OgAdoIv1heQ
    url: jdbc:postgresql://ep-gentle-fire-a4wvne1d.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          charset_name: UTF-8
          import_files: sql/user.sql,sql/role.sql,sql/module.sql,sql/permission.sql
        default_schema: main
settings:
  auth:
    token-time: 30
#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG